version: '3'
services:
  worker-service:
    build:
      context: worker-ejb
      dockerfile: wildfly/Dockerfile
    ports:
      - "8081:8081"
      - "9990:9990"
    depends_on:
      - postgres
      - consul
    networks:
      - worker-network
  postgres:
    image: postgres:13
    container_name: worker-postgres
    environment:
      - POSTGRES_DB=worker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ../Infrostructure/scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - worker-network

  consul:
    image: consul:1.11.3
    container_name: worker-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - worker-network

networks:
  worker-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 