version: '3'
services:
  worker-service:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=worker_db
      - CONSUL_HOST=consul
      # Payara System Properties
      - AS_ADMIN_PORT=4848
      - AS_ADMIN_LISTENER_PORT=4848
      - AS_INSTANCE_HTTP_PORT=8081
      - AS_INSTANCE_HTTPS_PORT=8181
      - AS_JMS_PORT=7676
      - AS_JMX_PORT=8686
      - AS_DEBUG_PORT=9009
      - AS_JAVA_DEBUGGER_PORT=9009
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - consul
    networks:
      - worker-network

  postgres:
    image: postgres:13
    container_name: worker-postgres
    environment:
      - POSTGRES_DB=worker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ../Infrostructure/scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - worker-network

  consul:
    image: consul:1.11.3
    container_name: worker-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - worker-network

networks:
  worker-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 