spring:
  application:
    name: worker-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s

server:
  servlet:
    context-path: /worker
  port: 8080 